### ISSUE TITLE
Events not registering

### ISSUE THREAD

**Issue by NatsuTwin** [AuroraLS3/Vault-Events#2]
Spigot version: 1.16.5
Vault version: latest
VaultEvents version: latest (b97187c)

Hello, I'm currently making an AccountProvider plugin to centralize players' data into one plugin which will communicate with others.
To achieve that, I need updating players' data everytime an action happens :
- I update their rank when it is changed
- And i use VaultEvents to use PlayerDepositEvent and PlayerWithdrawEvent.

But, when I do /eco give to a player, the events are not fired, even if they are registered.

On my onEnable:
`this.getServer().getPluginManager().registerEvents(new EconomyChangeListener(this), this);`

My listener class : 
`public record EconomyChangeListener(AccountProvider main) implements Listener {

    @EventHandler(priority = EventPriority.HIGHEST)
    public void onWithdraw(PlayerWithdrawEvent event) {
        System.out.println("Withdraw");
        // If the player is not online we don't have to modify his account because he does not have one
        if (!event.getOfflinePlayer().isOnline())
            return;

        main.getRepository().getFor(event.getOfflinePlayer().getPlayer()).ifPresentOrElse(account -> account.set("player-balance", account.getBalance() - event.getAmount())
        , () -> main.getLogger().severe("The account of the player " + event.getOfflinePlayer().getPlayer().getName() + " has not been found !"));
    }

    @EventHandler(priority = EventPriority.HIGHEST)
    public void onDeposit(PlayerDepositEvent event) {
        System.out.println("Deposit");
        // If the player is not online we don't have to modify his account because he does not have one
        if (!event.getOfflinePlayer().isOnline())
            return;

        main.getRepository().getFor(event.getOfflinePlayer().getPlayer()).ifPresentOrElse(account -> account.set("player-balance", account.getBalance() + event.getAmount())
     ,() -> main.getLogger().severe("The account of the player " + event.getOfflinePlayer().getPlayer().getName() + " has not been found !"));
    }

}`

The "Withdraw" and "Deposit" are never printed.
I have also set VaultEvents as a depend in my plugin.yml, just as Vault.

In the console Vault prints that it has succesfully hooked into Essentials Economy API and VaultEvents prints me this : 
https://prnt.sc/1yjixfj

Thanks in advance for your answer,
Regards,
Natsu

**Comment by AuroraLS3** [comment]
Hmm, my guess is that the economy wrap thing runs before your economy is registered. I can try to see if there is something to do to fix this, could you send me a copy of your plugin so I can use it for debugging

**Comment by NatsuTwin** [comment]
[provider.zip](https://github.com/AuroraLS3/Vault-Events/files/7492238/provider.zip)

**Comment by NatsuTwin** [comment]
Hello..?

**Comment by AuroraLS3** [comment]
Sorry I've been busy, I haven't been able to debug this issue yet.

**Comment by AuroraLS3** [comment]
Ok I looked at it and it seems that essentials registers its economy after VaultEvents has attempted to wrap the economy to send events
```
[11:11:06 INFO]: [VaultEvents] Enabling VaultEvents v1.7.1
[11:11:06 INFO]: [VaultEvents] Vault Events registered - Events can now be listened to.
[11:11:06 INFO]: [zAtreniaAccountProvider] Enabling zAtreniaAccountProvider v1.0
[11:11:06 INFO]: [zAtreniaAccountProvider] The account provider has been loaded !
[11:11:06 INFO]: [Essentials] Enabling Essentials v2.19.2
[11:11:07 INFO]: [Vault] [Economy] Essentials Economy hooked.
```

**Comment by AuroraLS3** [comment]
Upon further investigation it turns out that the VaultEvents properly wraps the economy, even if it is registered a bit later - but Essentials uses it's internal economy instead of going through Vault when using /eco give, bypassing VaultEvents completely.

You may also need to listen to Essentials `UserBalanceUpdateEvent`
